name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Lint
        run: |
          # Install SwiftLint if not already installed
          if ! command -v swiftlint &> /dev/null
          then
              brew install swiftlint
          fi
          # Run SwiftLint
          swiftlint --strict

      - name: Build
        run: |
          xcodebuild build \
            -project Scandalicious.xcodeproj \
            -scheme "Scandalicious NON-PROD" \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
            -skipPackagePluginValidation \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Test
        run: |
          xcodebuild test \
            -project Scandalicious.xcodeproj \
            -scheme "Scandalicious NON-PROD" \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
            -skipPackagePluginValidation
